spring:
  datasource:
    url: jdbc:mysql://localhost:3306/datastone?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: myroot
    password: 166618
    driver-class-name: com.mysql.cj.jdbc.Driver


#mybatis
mybatis:
  check-config-location: true
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.alearner.Model.*
  configuration:
    map-underscore-to-camel-case: true
#  config-location: classpath:mybatis-config.xml


#显示输出mybatis的执行sql
logging:
  level:
    com:
      alearner:
        Mapper: debug
